Lambda-School-Labs/labs9-employee-scheduler

pull_request_template.md

Added template to autofill PRs.
No tests required.

Created PR template to autofill PRs

---

README.md

Updated README formatting, no tests required, no breaking changes.

Made formatting changes to README

---

client/src/components/Billing.js
client/src/components/BreadCrumb.js
client/src/components/Calendar.js
client/src/components/CreateSchedule.js
client/src/components/EmployeeDashboard.js
client/src/components/Employees.js
client/src/components/Home.js
client/src/components/LeftSideBar.js
client/src/components/NavSide.js
client/src/components/PrivateRoute.js
client/src/components/Settings.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Added template components to the components folder for setup. These will be used as container functional or dumb components based on their needs.
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback
- [ x] I have performed a self-review of my …

adding template components

---

.eslintrc.js
README.md
__tests__/server.js
client/.eslintrc
client/package.json
client/src/__tests__/App.js
client/src/setUpTests.js
client/yarn.lock
jest.config.js
package.json
yarn.lock

This pull request adds the ability to perform both server and client side testing. Two minimal test examples are included, one for server, one for client. Tests for client and server must be run separately in the root of each.
Users will need to run yarn install in both the server and client roots as dependencies have been updated to include:
Server:
"eslint": "5.6.0", (updated version for compatibility)
"jest": "^23.6.0", (moved to dev dependencies)
"supertest": "^3.3.0"
Client:
"jest-dom": "^3.0.0",
"react-testing-library": "^5.4.4"
- [X ] This change requires a documentation update
- [X ] Complete, tested, ready to review and merge
Tests can be run successfully in root and client.
- [X ] My changes generate no new warnings

Inititialize testing

---

README.md
client/public/index.html
client/src/design/theme.js

Updated README to include front-end and back-end deployment URLs for convenience. Added the font "Open Sans" to the client, which will be used throughout the app. Began a design system to preset colors, fonts, spacing, etc. to enable DRYer styling. 
N/A

Updated README to include urls, added font, started design system

---

.env.development
client/src/App.js
client/src/components/PrivateRoute.js

Fixes routes
Fixes # (routes)
-Tested locally

Fixes the routes

---

client/package.json
client/src/components/Billing.js
client/src/components/BreadCrumb.js
client/src/components/Calendar.js
client/src/components/CreateSchedule.js
client/src/components/EmployeeDashboard.js
client/src/components/Employees.js
client/src/components/Home.js
client/src/components/LeftSideBar.js
client/src/components/NavSide.js
client/src/components/PrivateRoute.js
client/src/components/Settings.js
client/src/components/common/Button.js
client/src/components/common/LinkItem.js
client/src/components/common/NavItem.js

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Components

---

client/src/App.js

Removes duplicate route from app.js
No tests needed

/calender route was in app.js twice.  This removes one of them

---

client/src/App.js
client/src/design/theme.js

Moved fonts from design system to global styles in App.js. This is because we only have one font family that we are using globally.
Viewed font changes by viewing site locally.

Moved fonts from design system into global styles

---

README.md

Created initial Readme structure
Fixes #21 
No tests have been run, but the document was previewed in a markdown previewer.
- [NA] I have added tests that prove my fix is effective or that my feature works

Initial structuring of readme

---

client/src/components/common/Button.js
client/src/design/theme.js

Updated design system to include more presets, such as borders, shadows, padding. Used design system to create styles for the Button component using emotion. Future work will entail adding props to dynamically render the button.
Visually tested button sizing, coloration, etc. via opening the React app in my local browser.

Updated styles and added basic styles to Button component

---

server/routes/router.js
server/server.js

Added router for users with GET functionality in order to meet goals for this week. This will be used to display data to the front end.
N/A, this is work in progress.

Added router for users with GET functionality

---

client/src/__tests__/App.js

This adds a test for routing to the calendar within App.
It is itself a test.
- [] My changes generate no new warnings

implement first router test

---

README.md

Fixes API link in Readme
testing not necessary for a typo fix

fixes API link in table of contents

---

client/src/components/Form/index.js
client/src/components/Form/styles.css

Add a form component
Needs tests

Form component added

---

client/src/App.js
client/src/components/BreadCrumb.js
client/src/components/LeftSideBar.js

I formatted the navigation bar to include a logo, adjusted flex boxes, and added some margin.
Tested visually by looking at my local copy of our react client in my browser.

Formatted top navigation bar, specifically for homepage. WIP.

---

client/src/components/PrivateRoute.js

Created a privateRoute component to be used along side auth properties received from firebase through redux.
Adding component
- [ x ] New feature (non-breaking change which adds functionality)
- [ X ] Complete, but not tested (may need new tests)
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas

Privateroute

---

database/data_model.md

Wrote a doc detailing the data model and proposed database helpers
Docs update
No code has been changed. Just a new document.

Data model doc

---

client/src/components/BreadCrumb.js

changed sign-in route to be login, to conform to firebase PR

---

client/package.json
client/src/__tests__/App.js
client/testing/utils.js
client/yarn.lock

Return router tests to passing
Fixes #28 
This is a test

Return router tests to passing

---

client/src/actions/index.js
client/src/components/Login.js
server/config/customMiddleware/authenticate.js

Refactor to:
- remove a reliance on a .gitignored json file, instead making use of .env file
- make React app more robust to possible exceptions in login flow
- Codesplit firebase, removing console.warn message
Tests not implemented, as login flow is still in progress.
- [] I have made corresponding changes to the documentation

Refactor firebase

---

client/src/components/Register.js
client/src/components/common/SelectList.js

Adds Base structure to registration component for visualization of page
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [  ] There are no merge conflicts

completed base registration temp form

---

client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/Card.js
client/src/components/EmployeeCard/TimeOff.js
netlify.toml

There's a folder in our components subfolder called EmployeeCard. It contains a few components that can be composed into employee info cards, as shown here: https://trello.com/c/NBxEm0w3/32-employee-card and here: https://trello.com/c/UjlPWUh3/31-employee-sidebar
I also updated the netlify.toml to handle redirects
N/A, WIP

Created and left comments in employee cards components

---

client/public/index.html

Change title in index.html. That's it.
New title shows up in browser.

change page title to cadence

---

database/helpers/availabilitiesModel.js

Adds logic to two helper functions
It's been peer reviewed

adds logic to helper functions

---

database/helpers/eventsModel.js

Wrote out CRUD helpers for events model. Tests are to be written. Also wrote out a helper to get events by organization (rather than by user).
Tests are to be completed. Blocker is writing routes.

Wrote out helper functions for events model

---

client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/Card.js
client/src/components/EmployeeCard/TimeOff.js
client/src/components/Employees.js

Got employees cards rendering for the employees page with basic styling. No content yet
Renders properly

Employees cards

---

database/helpers/availabilitiesModel.js
database/helpers/timeOffRequestsModel.js

Adds logic to the helpers in timeOffRequestsModel.js
Has not been tested yet, but has been peer reviewed

Adam backend

---

server/routers/availabilitiesRouter.js

Added availability routes with comments for what is needed to function
- [ x] New feature (non-breaking change which adds functionality)
- [ x ] Complete, but not tested (may need new tests)
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] There are no merge conflicts

added availabilities routes using helper functions

---

server/routers/eventsRouter.js

These changes include CRUD routes for the events router. 
Tests will be added soon.

Events router

---

client/src/design/theme.js

Changed the design system according to the guidelines Josh Knell laid out.
n/a

Changed design system a bit per Josh lecture

---

server/routers/eventsRouter.js

Discovered some issues in the eventRouter.js file. For example, some routes were not passing the right arguments to the helper functions for the db. This would have caused future errors. Furthermore, one route was missing, which has been corrected.
N/A, tests are yet to be created

EventRouter fixes

---

database/helpers/organizationsModel.js

add uuid to organizations model helper

---

__tests__/usersRouter.js
database/migrations/20190108172400_users.js
database/migrations/20190108172418_availabilities.js
database/migrations/20190108172431_time_off_requests.js
database/migrations/20190108172442_events.js
database/utils/generateData.js
package.json

Implemented helping functions for testing and 3 tests for the user endpoint.
This implements tests.

Users test

---

__tests__/availabilitiesRouter.js

initiated route tests on availability helpers
- [ x] Test A
- [ x] Test B
- [ x] My code has been reviewed by at least one peer
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New …

started testing on availabilitiesRoute

---

client/src/App.js
client/src/components/BreadCrumb.js
client/src/components/Home.js
client/src/components/LeftSideBar.js
client/src/components/Settings.js

Sidebar is now toggleable based off a menu button and is positioned in the top left. The navbar now shows up on all pages, with the caveat that on the Home page it is fixed and on all other pages it is not.
Renders according to description in chrome.

Changes to sidebar and navbar

---

__tests__/availabilitiesRouter.js
database/helpers/availabilitiesModel.js
database/helpers/usersModel.js
server/routers/availabilitiesRouter.js

created tests for availability routes w/ help from Kam and tested for searches that show return no availability.
- [ x ] Test A
- [ x] My code has been reviewed by at least one peer
- [ x] I have made …

fixed edge cases tests and created more tests for availability routes

---

client/src/App.js
client/src/actions/employeesActions.js
server/config/customMiddleware/authenticate.js

This allows axios requests to pass through authentication middleware on server in a test environment. 
- All related tests pass. This is a network communication issue so testing will require e2e testing.

add testing loophole for auth

---

client/src/components/BreadCrumb.js
client/src/components/Register.js
client/src/components/common/SelectList.js
client/src/design/theme.js

Adding visual styling to the registration component, also added a few styles to the theme file
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback

completed a deeper styling in the register component

---

__tests__/organizationsRouter.js
database/helpers/organizationsModel.js
server/routers/organizationsRouter.js

Wrote GET and POST tests for the organizations router.
These are the tests for something else.

Org router tests

---

client/src/__tests__/App.js
client/src/__tests__/Register.js
client/src/components/BreadCrumb.js
client/src/components/Form/index.js
client/src/components/Register.js
client/src/components/common/SelectList.js
client/src/design/theme.js

Completed Testing on the registration component inputs, all tests pass
- [x ] Test A (react testing library)
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit …

Testing front end

---

README.md

Adds link to wireframe in README.md
no need to test

Adds link to wireframe in README.md

---

Procfile
__tests__/timeOffRequestsRouter.js
knexfile.js
package.json
server/index.js
server/routers/timeOffRequestsRouter.js

Created a Procfile for heroku to allow finer control over heroku scripts, and relocated index.js into server/. I added knex migrations to heroku startup to try to fix a bug where employees don't display on front end.
Ran tests, all passing.
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ X] There are no merge conflicts

Heroku updates

---

client/src/components/EmployeeDashboard.js

just adding mock data into state for employee dashboard, making it simple to plug in and replace later.
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback
- [ x] My code has been reviewed by at least one peer

adding state data to employee component for mock

---

client/src/components/EmployeeCard/Card.js
client/src/components/common/Button.js
client/src/components/common/OuterContainer.js
client/src/design/theme.js

Re-adjusted the design of the employee cards, shifted some colors, made some changes to the design system.
Visually tested in local browser

Adjusted numerous little design things

---

client/src/components/EmployeeCard/Card.js
client/src/components/common/CardContainer.js
client/src/design/theme.js

Added color to the employee cards, just for Samuel.
Verified visually in browser.

Added some color to the cards

---

database/helpers/dashboardHelper.js
database/helpers/index.js
package.json
server/routers/dashboardRouter.js
server/routers/index.js
server/server.js

Created the API endpoint for the employee dashboard route.
Postman.

Dashboard data route

---

client/src/components/EmpDashboardComp/AssignedShifts.js
client/src/components/EmpDashboardComp/TimeOffApproved.js
client/src/components/EmployeeDashboard.js

added Time off Request component to employee dashboard component with mock data
- [ x] New feature (non-breaking change which adds functionality)

Continue styling employee dashboard

---

__tests__/organizationsRouter.js
server/routers/organizationsRouter.js

I added the PUT and DELETE tests for the organizations router.
This is a test.

Completed CRUD tests for organizations router

---

client/src/__tests__/EmployeeDashboards.js
client/src/actions/employeesActions.js
client/src/components/EmployeeDashboard.js
client/src/reducers/employeesReducer.js

Created redux action and reducer to get employee by id for dashboard
- [x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
need to update from Dev to pull created backend function to make this work
- [x ] Incomplete/work-in-progress, PR is for discussion/feedback

Fetch single employee

---

__tests__/employeesRouter.js
database/helpers/employeesHelper.js

Wrote some preliminary tests for GET by id for employees router.
This is a test.

Began writing tests for employees router

---

client/src/components/EmployeeDashboard.js

completed basic time off approved box for employee dashboard, might need to go back for styling changes later.

added the approved time off box in the employee dashboard

---

client/src/actions/employeesActions.js
client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/Card.js
client/src/components/EmployeeCard/TimeOff.js
database/helpers/employeesHelper.js

Get availabilities and time off requests data displaying on employees page. To do so, refactored components, redux action, and backend db helper.

Add availabilities and time off requests to employees page

---

client/src/components/Settings.js

Started building out changeHandler and submitHandler functionality.
N/A, still WIP

Added some more functionality to settings

---

client/src/__tests__/App.js
client/src/__tests__/EmployeeDashboards.js
client/src/__tests__/Redux.js
client/src/actions/employeesActions.js
client/src/components/EmployeeDashboard.js
client/testing/utils.js

This was implemented so we are truly testing the component that is being used in our codebase. Also implemented the testing utility function, renderWithReduxAndRouter, which can be used to test components that need to make use of both Redux and React Router.

Refactored employeeDashboard test to import the project component

---

client/src/components/Settings.js

Settings page is almost done, bottlenecked by auth so that I can read logged-in user off the redux store. Otherwise, finished.
N/A, need to complete last 5% of functionality before testing.

Added changeHandler and submitHandler to settings

---

client/src/__tests__/Settings.js
client/src/components/EmployeeDashboard.js
client/src/components/Settings.js

Testing basic input functionality of Settings page
- [x ] Test A
- [x ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New …

Testing settings page

---

client/src/components/EmpDashboardComp/TimeOffRequest.js

Removes unused import
- [ X] Complete, tested, ready to review and merge
NO need, it was just removing an unused import

Time off requests

---

database/migrations/20190114155542_users_prefs.js
database/migrations/20190114160155_users_prefs.js
database/utils/generateData.js

Runs on the userRouter.js test. Test breaks due to a limitation in SQLite3 (storing bools as 0/1, instead of T/F)

Added preferences columns to users table

---

client/src/components/Billing.js

Basic billing form to test out Stripe.
n/a, wip

Created Billing form

---

server/routers/paymentRouter.js

Back-end code to create a Stripe "customer" object and assign them a "subscription" 
Waiting til front-end component is built.

Wrote up Stripe back-end code in paymentRouter.js

---

client/package.json
client/src/components/EmpDashboardComp/TimeOffApproved.js
client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/TimeOff.js
client/src/components/EmployeeDashboard.js

removes unnecessary date picker dependency
No need

removes unnecessary date picker dependency

---

client/package.json
client/public/index.html
client/src/App.js
client/src/components/Billing.js
client/yarn.lock
server/routers/paymentRouter.js

Completed Stripe front-end and back-end.
Successfully created customer and related subscription in Stripe via web form.

Completed Stripe integration

---

database/migrations/20190115173416_organizations_stripe.js

Added "paid" bool and "customer_id" string columns to organizations table. Info to be filled in as customers sign up and complete billing process.
passed 9/9 tests in organizationsRouter.js test

Added relevant fields to orgs table for Stripe integration

---

client/src/actions/employeesActions.js
client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/TimeOff.js
client/src/components/EmployeeDashboard.js
client/src/reducers/employeesReducer.js
database/helpers/timeOffRequestsModel.js
server/routers/timeOffRequestsRouter.js

Adds functionality for supervisors to manage time off requests on the employee page.
It works when the buttons are clicked on the employees page,

Disposition time off requests

---

.gitattributes

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
adding binary types for none text, binary files to hopefully fix image issues during deployment.
- [x ] My code has been reviewed by at least one peer
- [ x] There are no merge conflicts

Gitattributes fix maybe

---

client/src/components/EmpDashboardComp/TimeOffRequest.js
client/src/components/EmployeeCard/TimeOff.js
client/src/reducers/employeesReducer.js

added component that conditionally renders approve or deny button based on the status of the request on the employees page.
- [x ] New and existing unit tests pass locally with my changes

Optimize time off requests

---

client/src/components/Billing.js
client/src/components/CalendarView.js
client/src/components/CreateSchedule.js
client/src/components/EmployeeDashboard.js
client/src/components/Employees.js
client/src/components/Home.js
client/src/components/Settings.js

Removing location from state and passing it as a string to breadcrumb component. Also changing components that are stateless to functions for optimization. 

changed loctaion to be a string and statless components into functions

---

client/src/components/Calendar.js
client/src/components/Scheduler/index.js

Color codes events by user. 
Visually in browser.

Color coded events by user

---

client/src/App.js
client/src/actions/registerActions.js
client/src/components/RegisterOwner.js
client/src/reducers/registerReducer.js
server/routers/usersRouter.js

Redirect is working for register owner + org component. Also fixed server route that wasn't saving the correct user id. 
Works in browser and confirmed in db browser.

Get redirect working for register owner + org component

---

client/src/App.js
client/src/components/PrivateRoute.js

Implemented role-based access using the PrivateRoute component and access props. Implemented redirects the the `/` route based on user login status. 
Works for all routes tests in browser. Better backend integration is needed for more complete testing.

Implement role-based access in client

---

client/src/App.js
client/src/components/LeftSideBar.js

conditionally render side nav based on user role
- [x ] Complete, but not tested (may need new tests) *needs to be tested with other roles*
- [x ] New and existing unit tests pass locally with my changes

conditionally render the side nav based on user permissions or role

---

client/src/components/Calendar.js
client/src/components/Scheduler/DailySummary.js
client/src/components/Scheduler/WeekSummary.js
client/src/components/Scheduler/index.js
client/src/components/Settings.js

Created a summary component for the calendar. It will tell you at a glance how many employees are scheduled for how many hours.
lots of console.logs.

Created Daily Summary component with all requisite logic

---

client/src/components/Scheduler/index.js
client/yarn.lock

Resolving some small merge conflicts.

---

client/src/App.js
client/yarn.lock
yarn.lock

FIX issue with stripe preventing component loading

---

client/src/components/Settings.js

The settings page now enables users to edit their settings.

Settings component is completely live

---

client/src/components/HoursOfOperation.js
client/yarn.lock
database/data_model.md
database/helpers/hoursOfOperationModel.js
database/helpers/index.js
database/migrations/20190116223230_hours_of_operation.js
database/seeds/07_hours_of_operation.js
database/utils/generateData.js
server/routers/availabilitiesRouter.js
server/routers/hoursOfOperationRouter.js
server/routers/index.js
server/routers/timeOffRequestsRouter.js
server/server.js

Adds a migration, seed, and endpoints for Hours of Operation.
Used DB browser to make sure the seed is working.
Used postman to test the endpoints.

Hours of operation backend

---

client/src/components/Settings.js

Fixed checkbox behavior for settings form and made phone pattern more broadly accepting
#171 
Tested in browser

Select check

---

client/src/components/Billing.js
server/routers/organizationsRouter.js
server/routers/paymentRouter.js

Stripe is live and will enter data into the DB

---

server/config/customMiddleware/authenticate.js
server/config/customMiddleware/authorize.js
server/routers/availabilitiesRouter.js
server/routers/dashboardRouter.js
server/routers/employeesRouter.js
server/routers/eventsRouter.js
server/routers/organizationsRouter.js
server/routers/paymentRouter.js
server/routers/timeOffRequestsRouter.js
server/routers/usersRouter.js

Implements a first pass access control that locks down certain routes for access only by certain classes of users. Adds a testing loophole that can be used to specify certain classes of user. 
Access control works in Postman and app still works. Will need more tests.

Access control

---

__tests__/eventsRouter.js
__tests__/usersRouter.js
server/config/customMiddleware/authorize.js

See title. The 6th one appeared to be failing because we changed the datetime format, so I fixed that. But it's still failing because for some reason response.body is coming back undefined. I haven't been able to to figure it out.

Fix 5/6 failing express tests

---

__mocks__/firebase/app.js
client/src/__tests__/App.js
client/src/components/Login.js
client/src/components/RegisterOwner.js

Implemented a google route, removed account-chooser
Have gone through the login and register flow

Firebase google

---

client/src/components/Billing.js
client/src/components/Loader.js
client/src/components/Status.js
server/routers/paymentRouter.js

Fixed a bug preventing Stripe from working.

Fixed Stripe error, made progress on Redux

---

client/src/components/ErrorMessage.js
client/src/components/Loader.js
client/src/components/PrivateRoute.js
client/src/components/Settings.js

Updated EmptyPage.js and deleted ErrorMessage. Added status indicators to Settings.

---

client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/Card.js
client/src/components/EmployeeCard/TimeOff.js
client/src/components/common/CardContainer.js

Styled the time off component and the availability components for employee cards. Fixed a tiny Redux error in the time off component.

Styled the employee cards

---

client/src/components/Settings.js

The settings component is completely done.

Finished the settings component completely

---

client/src/actions/authActions.js
client/src/components/Settings.js
client/src/reducers/authReducer.js

Now, when you alter your settings, they are available via the redux store. No need to refresh to get up-to-date data.

Wired up Settings component to Redux

---

database/utils/generateData.js

Fixes the issue of both "confirmed" and "appoved showing up in the time-off component
I tested it on this branch first and it works fine.

fixes behavior on the issue @rd825 open about he time off component

---

client/src/components/Billing.js
client/src/components/Loader.js
client/src/components/Settings.js
client/src/components/Status.js
client/src/components/common/Button.js
server/routers/paymentRouter.js

I honestly forgot what I did in this PR. 
All I know is that billing is hooked up to redux now and that users can create and delete their subscriptions.

Billing redux

---

client/src/components/Footer.js
client/src/components/Home2.js

Finished up the pricing bit of the landing page, adjust some of the vertical spacing, added a placeholder for the video loop / gif we'll eventually add showcasing the product.
also added a Footer component;

Finished up landing page for now

---

client/src/components/EmployeeCard/Card.js

Conditionally render time_off_requests and availabilities in employee card
Tested in broswer development environment

Conditionally render time_off_requests and availabilities in employee card

---

client/src/App.js
client/src/components/Scheduler/EmployeePool.js
client/src/components/Status.js

Scrollbars

---

database/helpers/organizationsModel.js
database/utils/dbUtils.js
database/utils/generateData.js
knexfile.js

Move our local and production services over to postgres from sqlite3
Tests were run. Two server tests are failing now that will need to be updated.

Psql conversion

---

client/src/components/Billing.js
client/src/components/EmployeeCard/Card.js

Enables the ability to delete non-owner role users. Supervisors and owners can access this via an X on the top an employee card in directory view.

The ability to delete non-owner users

---

client/src/actions/eventActions.js
server/routers/eventsRouter.js

Fixes an issue on the server where deletions were not persisting.

Calendar delete hotfix

---

client/src/components/EmployeeCard/TimeOff.js
client/src/components/Settings.js

Fixed Edit button and indicated contact email. Updated time formatting

---

server/config/customMiddleware/authenticate.js

Misplaced parenthesis causing breaking.

fix issue with authenicate

---

client/src/App.js
client/src/components/EmployeeDashboard.js
client/src/reducers/employeesReducer.js
database/helpers/dashboardHelper.js
server/routers/dashboardRouter.js

Rewrote server side helper to match new event values for the shifts and days off (this was changed for the event before but left alone in this file 😠 ). Set a condition to only display denied requests that
- [x ] I have commented my code, particularly in hard-to-understand …

Change dashboard get user

---

client/src/components/Scheduler/index.js

Fixes a duplicated fetchHoursFromDB call in Scheduler component. This didn't have any effect but was clogging up the server pointlessly.

remove  mangled extra fetchHoursFromDB

---

client/src/components/AddEmployee.js
client/src/components/Employees.js
client/src/components/LeftSideBar.js

Created a form for owners and supervisors to add new roles. Owners can add supervisors and employees. Supervisors can only add employees.
Honestly, it hasn't.

Add Supervisors & Employees Functionality

---

client/src/actions/authActions.js
client/src/actions/registerActions.js
client/src/components/Login.js
client/src/components/RegisterOwner.js
client/src/components/Scheduler/index.js
client/src/reducers/authReducer.js
client/src/reducers/registerReducer.js

Pushes unrecognized login users to the register page. Also clears out Register reducer when Register unmounts, so prior registration states don't affect future ones
Tested in browser.

Handle unknown login and clear register state after register

---

client/src/components/Billing.js
client/src/components/Settings.js

Added some extra info on the settings and billing pages

---

client/src/actions/employeesActions.js
client/src/actions/eventActions.js
client/src/components/Calendar.js
client/src/components/EmployeeCard/Card.js
client/src/components/EmployeeCard/TimeOff.js
client/src/components/EmployeeDashboard.js
client/src/components/Employees.js
client/src/components/Scheduler/index.js
client/src/design/theme.js

See title. 
Potential breaking change from axios call adjustments.
N/A

Added colors to event color array, added breakpoints to design system, adjusted axios calls to use token not 'testing'

---

client/src/components/BreadCrumb.js
client/src/components/LeftSideBar.js

See title, non-breaking styling changes, no tests needed.

Finished responsive top nav and side nav

---

client/src/components/BreadCrumb.js
client/src/components/EmployeeCard/Card.js
client/src/components/Employees.js
client/src/components/Home.js
client/src/design/theme.js

See title, non-breaking styling changes, no tests needed.

Made landing page responsive (spans my laptop 1600px width to mobile ~400px width)

---

client/src/components/Scheduler/index.js
client/src/utils/index.js

A utility for fixing the display of dates on employee cards
Tested visually in DOM

format dates utility

---

client/src/components/AddEmployee.js
client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/Card.js
client/src/components/HoursOfOperationModal/Button.js
client/src/components/HoursOfOperationModal/index.js
client/src/components/LeftSideBar.js
client/src/components/common/OuterContainer.js

See title, non-breaking styling changes, no tests needed.

Fixed OuterContainer height, avails formatting on emp cards, emp card width, "role" label rendering on addEmp form, and animations on HOO modal

---

client/src/components/Scheduler/ResourceCard/Availability.js

Fixes a typo causing imports to break.

utils hot fix

---

client/src/components/Scheduler/DropCal.js
client/src/components/Scheduler/EmployeeResource.js
client/src/components/Scheduler/index.js
client/src/utils/index.js

Color calendar slots that aren't droppable using the shift validation utility. Probably we can select better styling to express this but I'm glad we have the functionality.
Tested in the browser development setting

implement colorization for possible drop slots on calendar

---

database/helpers/timeOffRequestsModel.js
server/routers/timeOffRequestsRouter.js

Fixed an issue where time_off_requests weren't updating client side by updating the databade model helper.
Fixes #252 
Tested in development browser.

Fixed an issue where time_off_requests weren't updating client side

---

client/src/components/AddEmployee.js
client/src/components/BreadCrumb.js
client/src/components/Home.js
client/src/components/LeftSideBar.js
client/src/components/Scheduler/DailySummary.js
client/src/components/Scheduler/EmployeeResource.js
client/src/components/Scheduler/index.js
client/src/components/common/FormContainer.js

Samuel has a priority list for today, I cranked through a bunch of those.

Made small styling fixes

---

client/src/reducers/availabilityReducer.js
client/src/reducers/coverageReducer.js
client/src/reducers/employeeReducer.js
client/src/reducers/employeesReducer.js
client/src/reducers/hoursReducer.js
client/src/reducers/paymentReducer.js
client/src/reducers/registerReducer.js

FIX: react-redux store was not resetting on logout. This fix adds the reducer log out case to all reducers and will return the store to initial state.
- [ x] Bug fix (non-breaking change which fixes an issue)

added logout case to all reducers to clear redux store on log out

---

client/src/components/HoursOfOperationModal/index.js
client/src/components/LeftSideBar.js

Faster side nav and hours of operation transition

made faster modal transition

---

client/src/utils/index.js
database/data_model.md

Update shift validation to reference off property on availability data model.
Tested in browser to make sure validate behaves as expected.

Fix how availabilities interact with shift validation

---

client/src/App.js
client/src/components/AddEmployee.js
client/src/components/BreadCrumb.js
client/src/components/Employees.js
client/src/components/LeftSideBar.js
client/src/components/Modal.js
client/src/components/Scheduler/EmployeePool.js
client/src/components/common/FormContainer.js

Converted slide-out add employee modal into a true modal. Created Modal render props pattern.
Visually in browser

Add employee modal

---

client/src/components/Home.js
client/src/components/LeftSideBar.js

non-breaking styling changes, no tests needed.

Increased animation speed for sidebar, got rid mobile home page animations

---

client/src/components/BreadCrumb.js
client/src/components/EmployeeDashboard.js
client/src/components/LeftSideBar.js
client/src/components/Scheduler/EmployeePool.js

just moving bits around, no tests needed.

Added name to topnav, logout to side

---

client/src/components/Calendar.js
client/src/components/CreateSchedule.js
client/src/components/Scheduler/CoverageBadge.js
client/src/components/Scheduler/WeekSummary.js
client/src/components/Scheduler/index.js
client/src/components/common/Alert.js

Pushed buttons 40px in to line up with edges of calendar. Gave badge border and text color to stand out from buttons; made background white. Made calendar LR padding disappear on mobile to make it less constricted.

Adjusted button margins on cal page, made badge not look like button

---

client/src/components/Home.js
database/helpers/employeesHelper.js
database/static_seed.json

Adjusted employees helper SQL query to sort returned emps by first name (A -> Z)
In browser

Sort employees by first name

---

client/src/components/Scheduler/index.js

Toggle button now conditionally renders "Day View" or "Week View"

Made view toggle more descriptive

---

client/src/components/Employees.js
client/src/components/HoursOfOperation/Checkbox.js
client/src/components/HoursOfOperation/HOOSlider.js
client/src/components/HoursOfOperation/Status.js
client/src/components/HoursOfOperation/index.js
client/src/components/HoursOfOperation/styles.css

Styling for modal, non-breaking changes, no tests needed.

Styled HOO modal

---

client/src/components/Scheduler/ResourceCard/index.js
client/src/img/drag.svg

Adds drag and drop icon to resource cards.
k
It works in chrome

Adds drag and drop icon

---

client/src/components/Scheduler/Demo/steps.js
client/src/components/Scheduler/EmployeePool.js
client/src/components/Scheduler/ResourceCard/Availability.js
client/src/components/Scheduler/ResourceCard/TimeOff.js
client/src/components/Scheduler/index.js

Added friendlier and more detailed tutorial steps to explain more parts of the schedule page.

Add better tutorial steps

---

client/src/components/Employees.js

added a filter function to the employees page, works exactly the scheduler page.
- [x ] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts

created filter search for employees component

---

client/src/components/Billing.js
client/src/components/LeftSideBar.js
client/src/components/RegisterOwner.js
client/src/components/common/FormContainer.js

UX changes

---

client/src/components/EmployeeCard/Card.js

We can now click to email employees 😄 
Email client opens with the email address pre-populated

click to email

---

database/helpers/dashboardHelper.js

Adjusted the dashboardHelper to return the off boolean, which it wasn't getting before.

Fixed unavails on dash

---

client/src/components/RegisterOwner.js

Adds an escape route when there is a firebase token, but no matching user in the db.  
Works when tested in Chrome

Cancel registration button

---

database/migrations/20190108172400_users.js

added 2 boolean to the user schema to show if a user has visited a page before. This will be used for first time demo events.
- x[x ] My code follows the style guidelines of this project
- [x ] New and existing unit tests pass locally with my changes

added visit booly to user model

---

client/src/actions/employeesActions.js
client/src/components/Availability/AvailabilityForm.js
client/src/components/EmployeeCard/Availability.js
client/src/components/EmployeeCard/TimeOff.js
client/src/components/EmployeeDashboard/TimeOffApproved.js
client/src/components/EmployeeDashboard/TimeOffRequest.js
client/src/components/HoursOfOperation/index.js
client/src/components/Scheduler/ResourceCard/Availability.js
client/src/components/Scheduler/ResourceCard/TimeOff.js
client/src/utils/index.js
database/helpers/dashboardHelper.js
server/routers/timeOffRequestsRouter.js

Update hours of operation modal, edit availability modal, and time off request display and creation to support time zones
works in browser

Timezone dev modals

---

client/src/components/Scheduler/index.js
database/utils/demoUsers.js
server/routers/employeesRouter.js

Programmatically create 2 dummy accounts for new users to play with.
Locally in browser.

Create 2 demo employees for new users.

---

client/src/components/Scheduler/Demo/calendar.js
client/src/components/Scheduler/index.js
client/src/utils/index.js
database/migrations/20190108172400_users.js
database/utils/demoUsers.js
server/routers/employeesRouter.js
server/routers/usersRouter.js

Merge latest from master into timezone dev

---

client/src/components/Scheduler/index.js
client/src/utils/index.js

Fixes bugs where coverage wasn't discounting days business wasn't open and with shift overlap blocking. 
Manual browser testing.

Bug fixes for coverage and validation

---

client/package.json
client/src/components/Billing.js
client/src/components/Home.js
client/src/components/RegisterOwner.js
client/src/components/Scheduler/index.js
client/yarn.lock
database/utils/demoUsers.js
server/routers/employeesRouter.js

Converted demoUser avails and TORs to new time format

---

client/src/components/RegisterOwner.js
database/helpers/organizationsModel.js
database/migrations/20190115173416_organizations_stripe.js
server/routers/usersRouter.js

Should make register work again. Took me 15 minutes to merge 2 lines of code #winning
Fixes the issue locally

Register hotfix

---

README.md
docs/TDD.md
docs/data_model.md

Updates documentation and expands on read me.

Fixing docs

---

README.md
client/public/index.html
docs/TDD.md
docs/data_model.md

Seo meta tag

---

client/src/components/Scheduler/index.js
database/helpers/organizationsModel.js
database/utils/demoUsers.js
server/routers/usersRouter.js

Fixed broken UTC offset, solved problems with demo users.
Tested in browser.

Fixed UTC offset issues

---

client/src/components/EmployeeDashboard.js
client/src/components/EmployeeDashboard/DashCal.js
client/src/components/Scheduler/DropCal.js
client/src/components/Scheduler/index.js

Calendar works on employee dashboard.  More buttons needs to be added for added functionality and we need to figure out why the colors aren't working.
Works in Chrome

Dashboard calendar

---

client/src/components/EmployeeDashboard.js
client/src/components/EmployeeDashboard/DashCal.js

non-breaking styling change, no tests needed.

Got dash cal to color correctly

---

server/routers/availabilitiesRouter.js
server/routers/organizationsRouter.js
server/routers/timeOffRequestsRouter.js
server/routers/usersRouter.js

All endpoints were commented out last week. All this PR does it remove the commented out code.

Cleanup deprecated endpoints

---

client/src/components/LeftSideBar.js

just removed shift scheduler link from employee sidebar nav
- [ x] There are no merge conflicts

small change to remove scheduler link from employee nav

---

client/src/App.js
client/src/components/About.js
client/src/components/BreadCrumb.js
client/src/components/Footer.js
client/src/components/Legal.js

Finished terms and privacy, started about page

---

client/src/components/Employees.js
client/src/components/Scheduler/index.js

Made tut unskippable for first time users

---

__tests__/timeOffRequestsRouter.js
__tests__/usersRouter.js

Completed all server side testing for timeOffRequestRouter, also fixed a bad test in the userRouter.
- [x ] Test A
- [x ] Test B
- [x ] I have made corresponding changes to the documentation
- [ x] I have added tests …

Attempt backend testing

---

client/src/components/Scheduler/index.js

Fix slot colorization validation bug where events were assumed to be 60 minutes
Tested in browser for fix

fix validateDrop for halfhour events

---

client/package.json
client/public/index.html
client/src/components/EmployeeDashboard/TimeOffApproved.js
client/src/index.js
client/yarn.lock

Removed font-awesome and refactored to use WebFontLoader instead of <link> font import. This addresses some issues mentioned in Lighthouse report
Works in browser

addressed some lighthouse issues

---

client/src/components/Join.js
client/src/components/RegisterOwner.js

Adds a checkbox requiring the user to agree to terms of service and the privacy policy before they can complete registration.
Works fine in chrome.  No errors

Terms checkbox for register and join

---

client/package.json
client/src/components/EmployeeDashboard/TimeOffRequest.js
client/yarn.lock

Refactors to using a date-picker for cross-browser compatability
.
Tried it in both chrome and safari.

Date picker

---

client/src/components/Scheduler/EmployeePool.js

Fix search bar being shoved downwards on shift scheduler page
Tested in dev

fix search bar

---

client/src/components/Team.js

styling change, no testing needed.

Added Samuel bio and all relevant links

---

client/src/App.js
client/src/components/Demo/calendar.js
client/src/components/Employees.js
client/src/components/HoursOfOperationForm.js
client/src/components/Scheduler/index.js

cleared out most errors except the one that is caused by the demo redirecting from calendar page to employees page.

Clear errors

---

client/src/components/Demo/calendar.js
client/src/components/Employees.js
client/src/components/HoursOfOperationForm.js
client/src/components/Scheduler/index.js

removed scrolling from joy ride due to weird behavior and sling shot affect.
- [ x] Complete, tested, ready to review and merge
- [ x] My code has been reviewed by at least one peer
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that …

removed scrolling from demo due to bugs

---

__tests__/dashboardRouter.js
__tests__/hoursOfOperationRouter.js
client/src/__tests__/Employees.js
client/src/__tests__/Scheduler.js
client/src/__tests__/Settings.js
client/src/actions/authActions.js
client/src/actions/employeesActions.js
client/src/components/EmployeeDashboard.js
server/routers/dashboardRouter.js
server/routers/usersRouter.js

Add tests for various endpoints. Adjust `/users/current` and `/dashboard` endpoints and their client integration.

Add more backend testing

---

client/src/components/AddEmployee.js

Added a 20-user limit to the Pro plan. Added some conditional rendering to the maxed-out alert depending on which plan the user is on.

Added 20-user limit to Pro plan

---

client/package.json
client/src/App.js
client/src/components/Login.js
client/src/components/PrivateRoute.js

Introduced code splitting for components containing Calendar and firebaseUI to encourage faster initial load.
Also removed components no longer being used from App imports.
Tested in browser, works.

Code split

---

client/src/components/Calendar.js
client/src/components/PrivateRoute.js

styling change. no tests needed.

Overrode calendar styling to change border color: now 0.75px solid black.

---

client/yarn.lock
docs/TDD.md

Fixed bad formatting, removed description of how to write the document, added the name Cadence to the user story, added Hooks and Suspense to summary.
No need

Readable TDD

---

README.md
client/src/index.js

Change over to using basic NODE_ENV on front end since we get that for free
Brings back redux dev tools in dev without changing .env

move over to NODE_ENV usage in CRA

---

client/src/components/EmployeeDashboard/TimeOffRequest.js
docs/TDD.md

Removes alert for time off requests
Dev tested in chrome

Remove time off alert

---

__tests__/email.js
__tests__/invitesRouter.js
package.json
server/utils/email.js
yarn.lock

testing functionality of the mailing api server side
- [x ] Test A
- [ x] Test B
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my …

Testing mail stuff

---

client/src/components/Billing.js

Adds a conditional that makes it clear that the owner has paid and what they are getting when they re-visit the billing page AND they are a paid subscriber.
Dev tested in chrome

Adds conditional for paid owners that re-visit the page

---

__tests__/paymentRouter.js
package.json
server/routers/paymentRouter.js

Add tests for the back end stripe implementation. Made changes to the payments router where necessary (where bugs were occurring).

Testing stripe back end implementation

---

README.md
docs/API.md

Fix various spelling errors and updated a few things that have changed.

Misc changes to docs

---

client/src/components/CreateSchedule.js

refactored create schedule to use hooks, all works great and nothing is broken, why was this so easy to do? Is this still even react bros?
- [ x] Complete, but not tested (may need new tests)
- [x ] I have made corresponding changes to the documentation
- [x ] New and …

Refactor create schedule to hooks

---

client/src/components/Login.js

small functional refactoring of the login component from a class to a function for optimization.
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Complete, but not tested (may need new tests)
- [x ] Test A
- [ x] There are no merge conflicts

refactored login component

---

client/src/components/HoursOfOperationForm.js

consolidate state hooks for the day and time state to make them more modular within the scope.

fixed hooks in HOO to be separate states

---

client/src/views/Employees.js

Hamburger now stays with the top bar on the employees page
Dev tested in chrome

fixes hamburger

---

client/src/components/AddEmployee.js

There was some text rendering at 10px. I fixed it.

Fixed font-sizing for add employee modal

---

client/src/components/Demo/employees.js

Updated the number of users for free plan

Fixed misleading text in demo

---

client/src/components/AddEmployee.js
client/src/components/HoursOfOperationForm.js
client/src/components/Modal.js
client/src/design/theme.js

Brought modals back to behaving appropriately and responsively to different content sizes on tablet and mobile sizes.
Tested in dev browser

fix modals for tablet and responsive

---

client/src/components/AddEmployee.js

We all pair programmed this, so no need for further explanation I think.

Removed paid user cap

---

client/src/App.js
client/src/actions/authActions.js
client/src/reducers/authReducer.js
client/src/views/Join.js

Left the logout button, but now clicking it doesn't require a redirect, but leaves the user on the same page, and brings up the login component.
Tested in browser

Improve logout button

---

Procfile

Removes auto migration and seeding on production server. These must now be done manually through heroku when desired.
This deployed properly to heroku staging server.

remove auto migrate

---

client/src/views/Join.js

This is a purely cosmetic change in how we tell the user to logout on the Join page based on the latest and greatest flow.
This just is an update to page text.

fix wording of Join logout option

---

README.md

Needed to redescribe how to get this .env based on reading Rahul's guidance to Brian
This only affects Readme

correction to readme for STRIPE_PLAN_ID

---

client/src/components/Scheduler/index.js
client/src/views/Employees.js

Checks to see if the screen width is currently mobile. If it is, it will not mount the ReactJoyride component. Otherwise it behaves normally.
Works in dev environment.

No tutorial for mobile

---

README.md
client/src/components/Scheduler/index.js
client/src/views/Employees.js

Merging PTS to master, which contains the following fix:
- #442: Remove tutorial from mobile
Tested, and works in PTS deploy: https://pts--cadence.netlify.com/
No explicit tests were added to test for no tutorial functionality.

Remove tutorial from mobile
